# Generated by Django 5.2.13 on 2026-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
