# Generated by Django 5.2.13 on 2026-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
